language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_d9c3e000f1e1_key -iv $encrypted_d9c3e000f1e1_iv
  -in nannan_rsa.enc -out nannan_rsa -d
- chmod 600 nannan_rsa
- echo -e "Host 39.106.195.101\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- gulp
- scp -r build root@39.106.195.101
